name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  jest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run jest tests
        run: npm run test

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: path/to/test-results

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Upload lint results
        uses: actions/upload-artifact@v2
        with:
          name: lint-results
          path: path/to/lint-results

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, jest]

    if: needs.lint.result == 'success' && needs.jest.result == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Download test and lint results
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: path/to/test-results

      - name: Deploy static site to S3 bucket
        run: |
          aws --version
          aws configure list
          aws s3 sync . s3://s3testpipeline --debug

      - name: Cleanup
        run: rm -rf node_modules dist
